### ISSUE TITLE
canmonitor is broken

### ISSUE THREAD

**Issue by icolwell-as** [astuff/kvaser-linuxcan#4]
Current Ubuntu 18.04 release has a broken canmonitor example.

Running `./canmonitor 0` results in the following:

```
(398) ERROR FRAME flags:0x20 time:80
(399) ERROR FRAME flags:0x20 time:80
(400) ERROR FRAME flags:0x20 time:80
(401) ERROR FRAME flags:0x20 time:80
(402) ERROR FRAME flags:0x20 time:80
(403) ERROR FRAME flags:0x20 time:80
(404) ERROR FRAME flags:0x20 time:80
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
(405) ERROR FRAME flags:0x20 time:80
(406) ERROR FRAME flags:0x20 time:80
(407) ERROR FRAME flags:0x20 time:80
(408) ERROR FRAME flags:0x20 time:80
(409) ERROR FRAME flags:0x20 time:80
(410) ERROR FRAME flags:0x20 time:80
(411) ERROR FRAME flags:0x20 time:80
(412) ERROR FRAME flags:0x20 time:80
(413) ERROR FRAME flags:0x20 time:81
(414) ERROR FRAME flags:0x20 time:81
(415) ERROR FRAME flags:0x20 time:81
CAN Error Event
```

**Comment by icolwell-as** [comment]
Seems to generate the same output when installing canlib straight from kvaser source. Nothing we can do to fix this.

**Comment by Finedl** [comment]
Hi， fix this？ How to troubleshoot?

**Comment by icolwell-as** [comment]
Hi @Finedl , this repo is just a copy of Kvaser Linux Drivers and SDK from https://kvaser.com/download/

We just host them here for convenience and to be able to release them.
If you want a fix to this issue, I suggest finding a version of the SDK from kvaser's website that has a fix, or reaching out to KVaser directly to report the issue.
We do not modify the code in this repo, only update it with new content from kvaser.

**Comment by Finedl** [comment]
okok, I fix it !
