### ISSUE TITLE
netdev support

### ISSUE THREAD

**Issue by xR3b0rn** [astuff/kvaser-linuxcan#8]
Any plans for supporting netdev?

**Comment by icolwell-as** [comment]
What is netdev? Kvaser supports socketcan if that is what you are looking for.

BTW, this repo is just a github-hosted copy of whatever Kvaser releases as their SDK found here:
https://www.kvaser.com/download/

We don't modify the code at all.

**Comment by xR3b0rn** [comment]
Every iface you can see, when running `ifconfig`, has a netdev-driver implemented.

The netdev driver is already merged into the Linux source: https://github.com/torvalds/linux/blob/master/drivers/net/can/usb/kvaser_usb

Did not know that, thanks.

**Comment by xR3b0rn** [comment]
The netdev driver can be downloaded out of tree from: https://www.kvaser.com/download/?utm_source=software&utm_ean=7330130982192&utm_status=latest

**Comment by icolwell-as** [comment]
Thanks for the links and explanation!
